/* 
    >EncounterActions
    AddCombatantFromStatBlock
    AddCombatantFromState
    RemoveCombatant
    StartEncounter
    EndEncounter
    ClearEncounter
    CleanEncounter
    RestoreAllPlayerCharacterHP
    NextTurn
    PreviousTurn

    >CombatantActions
    SetStatBlock
    ApplyDamage
    ApplyHealing
    ApplyTemporaryHP
    SetInitiative
    LinkInitiative
    AddTag
    RemoveTag
    UpdateNotes
    SetAlias
    ToggleHidden
    ToggleRevealedAC
    MoveDown
    MoveUp
*/
